"""add transaction history table

Revision ID: 1c1b081aac6f
Revises: b174e6d90757
Create Date: 2025-05-04 10:41:05.004914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1b081aac6f'
down_revision = 'b174e6d90757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('products', 'default_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('default_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
