"""Create payment and transaction models

Revision ID: 4ab1493cf708
Revises: 8076e0c6a446
Create Date: 2025-05-11 07:56:00.188267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ab1493cf708'
down_revision = '8076e0c6a446'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'subtotal')
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'shipping_carrier')
    op.drop_column('orders', 'tracking_number')
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'order_id')
    op.drop_constraint('transaction_history_order_id_fkey', 'transaction_history', type_='foreignkey')
    op.drop_column('transaction_history', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_history', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('transaction_history_order_id_fkey', 'transaction_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
