"""add transaction history table

Revision ID: b174e6d90757
Revises: 5a21f70e754d
Create Date: 2025-05-04 10:19:46.867745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b174e6d90757'
down_revision = '5a21f70e754d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.drop_index('ix_product_details_attribute_key', table_name='product_details')
    op.drop_index('ix_product_details_attribute_type', table_name='product_details')
    op.drop_index('ix_product_details_id', table_name='product_details')
    op.drop_index('ix_product_details_product_id', table_name='product_details')
    op.drop_table('product_details')
    op.drop_index('ix_productattributetemplate_id', table_name='productattributetemplate')
    op.drop_table('productattributetemplate')
    op.drop_index('ix_product_images_id', table_name='product_images')
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_index('ix_products_shop_id', table_name='products')
    op.drop_constraint('products_shop_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'shop_id')
    op.drop_constraint('transaction_history_order_id_fkey', 'transaction_history', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_history', type_='foreignkey')
    op.create_foreign_key('transaction_history_order_id_fkey', 'transaction_history', 'orders', ['order_id'], ['id'])
    op.add_column('products', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_shop_id_fkey', 'products', 'stores', ['shop_id'], ['id'])
    op.create_index('ix_products_shop_id', 'products', ['shop_id'], unique=False)
    op.drop_column('products', 'quantity')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_index('ix_product_images_id', 'product_images', ['id'], unique=False)
    op.create_table('productattributetemplate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attribute_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_rules', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='productattributetemplate_pkey')
    )
    op.create_index('ix_productattributetemplate_id', 'productattributetemplate', ['id'], unique=False)
    op.create_table('product_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('attribute_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('value_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('value_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_details_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_details_pkey')
    )
    op.create_index('ix_product_details_product_id', 'product_details', ['product_id'], unique=False)
    op.create_index('ix_product_details_id', 'product_details', ['id'], unique=False)
    op.create_index('ix_product_details_attribute_type', 'product_details', ['attribute_type'], unique=False)
    op.create_index('ix_product_details_attribute_key', 'product_details', ['attribute_key'], unique=False)
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
