"""add transaction history table

Revision ID: eb9aea76b6db
Revises: 71297cb99421
Create Date: 2025-05-04 11:15:01.686372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9aea76b6db'
down_revision = '71297cb99421'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
