"""add transaction history table

Revision ID: f552da6b84e4
Revises: eb9aea76b6db
Create Date: 2025-05-04 12:26:27.287058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f552da6b84e4'
down_revision = 'eb9aea76b6db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_index('ix_stores_store_name', table_name='stores')
    op.drop_table('stores')
    op.drop_constraint('order_items_store_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'store_id')
    op.drop_constraint('promotions_store_id_fkey', 'promotions', type_='foreignkey')
    op.drop_column('promotions', 'store_id')
    op.drop_constraint('purchase_history_store_id_fkey', 'purchase_history', type_='foreignkey')
    op.drop_column('purchase_history', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_history', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_history_store_id_fkey', 'purchase_history', 'stores', ['store_id'], ['id'])
    op.add_column('promotions', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('promotions_store_id_fkey', 'promotions', 'stores', ['store_id'], ['id'])
    op.add_column('order_items', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_items_store_id_fkey', 'order_items', 'stores', ['store_id'], ['id'])
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stores_pkey')
    )
    op.create_index('ix_stores_store_name', 'stores', ['store_name'], unique=False)
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    # ### end Alembic commands ###
